# Generated by Django 3.0.5 on 2020-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, 'high'), (2, 'medium'), (3, 'low')], default='1', max_length=3),
        ),
    ]
