# Generated by Django 3.0.5 on 2020-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201113_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='on_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='on_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
