# Generated by Django 3.0.5 on 2020-11-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201113_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='on_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='on_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
