# Generated by Django 3.0.5 on 2020-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201113_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='on_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='on_time',
            field=models.TimeField(),
        ),
    ]
